# Generated by Django 5.1.3 on 2024-11-17 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('Especialista', 'Profundidade de conhecimento em um campo específico.'), ('Inovador', 'Busca por ideias novas, disruptivas.'), ('Colaborador', 'Prefere compartilhar e discutir ideias.'), ('Comunicador', 'Focado em artigos que podem ser comunicados ao público.'), ('Analista', 'Preocupado com a qualidade dos dados e a metodologia.')], max_length=100, verbose_name='profile')),
                ('research_title', models.CharField(max_length=100, verbose_name='research title')),
                ('research_description', models.TextField(max_length=500, verbose_name='research_description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
